In [18]:
import torch

# Detect GPU (MPS for Apple Silicon)
device = "mps" if torch.backends.mps.is_available() else "cpu"
print("Using device:", device)


Using device: mps


In [ ]:
# -----------------------
# Section 1: Broadcasting
# -----------------------

v = torch.rand(3,)
M = torch.rand(3, 4)
print("v + M:", v.reshape(3,1) + M)

c = torch.rand(3,1)
r = torch.rand(1,4)
print("\n\nc + r:", c * r)

d = torch.full((5,5), 1.0)
s = torch.rand(1,5)
print("\n\nd:", d)
print("s:", s)
print("d scaled by s", d * s)

v + M: tensor([[1.2945, 1.2947, 1.4338, 0.8973],
        [0.7590, 1.0965, 1.0888, 1.4868],
        [1.5870, 0.7570, 1.0631, 1.4536]])


c + r: tensor([[0.8240, 0.4415, 0.4069, 0.6153],
        [0.8800, 0.4716, 0.4345, 0.6571],
        [0.4400, 0.2358, 0.2173, 0.3285]])


d: tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
s: tensor([[0.2621, 0.4580, 0.7923, 0.9655, 0.4517]])
d scaled by s tensor([[0.2621, 0.4580, 0.7923, 0.9655, 0.4517],
        [0.2621, 0.4580, 0.7923, 0.9655, 0.4517],
        [0.2621, 0.4580, 0.7923, 0.9655, 0.4517],
        [0.2621, 0.4580, 0.7923, 0.9655, 0.4517],
        [0.2621, 0.4580, 0.7923, 0.9655, 0.4517]])


In [ ]:
# -----------------------
# SECTION 2 — Reductions (mean, sum, norms)
# -----------------------

A = torch.arange(1., 13., device=device).reshape(3, 4)
print("\nTensor A:\n", A)
print("Row wise Mean:\n", torch.mean(A, dim=1))
print("Column wise Mean:\n", torch.mean(A, dim=0))
print("Sum of all elements in A:", torch.sum(A))
print("Row wiseL2 Norm of A:", torch.norm(A, p=2, dim=1))

B = torch.arange(1., 51., device=device).reshape(5, 10)
print("\n\n5 vectors of 10 length:\n", B)
print("max of each vector:", B.max(dim=1).values)
print("Index of Max of each vector:", B.argmax(dim=1))
print("Vector with greatest sum:", B[B.sum(dim=1).argmax()])


Tensor A:
 tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], device='mps:0')
Row wise Mean:
 tensor([ 2.5000,  6.5000, 10.5000], device='mps:0')
Column wise Mean:
 tensor([5., 6., 7., 8.], device='mps:0')
Sum of all elements in A: tensor(78., device='mps:0')
Row wiseL2 Norm of A: tensor([ 5.4772, 13.1909, 21.1187], device='mps:0')


5 vectors of 10 length:
 tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.],
        [31., 32., 33., 34., 35., 36., 37., 38., 39., 40.],
        [41., 42., 43., 44., 45., 46., 47., 48., 49., 50.]], device='mps:0')
max of each vector: tensor([10., 20., 30., 40., 50.], device='mps:0')
Index of Max of each vector: tensor([9, 9, 9, 9, 9], device='mps:0')
Vector with greatest sum: tensor([41., 42., 43., 44., 45., 46., 47., 48., 49., 50.], device='mps:0')


In [82]:
# -----------------------
# SECTION 3 — Indexing + Masking
# -----------------------

A = torch.arange(1., 26., device=device).reshape(5, 5)
print("Tensor A:", A)
print("Diagonal of A:", A.diag().diag())
print("Diagonal of A as 0:", A.fill_diagonal_(0))
print("Elements greater than A.mean():", A[A > A.mean()])

B = torch.randint(1,101,(10,10))
print("\n\nTensor B:\n", B)
print("Mask for even numbers in B:\n", B[B%2 == 0])
B_zeroed = B.clone()
B_zeroed[B < 50] = 0
print("Mask for numbers less than 0.5 in B:\n", B_zeroed)

Tensor A: tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25.]], device='mps:0')
Diagonal of A: tensor([[ 1.,  0.,  0.,  0.,  0.],
        [ 0.,  7.,  0.,  0.,  0.],
        [ 0.,  0., 13.,  0.,  0.],
        [ 0.,  0.,  0., 19.,  0.],
        [ 0.,  0.,  0.,  0., 25.]], device='mps:0')
Diagonal of A as 0: tensor([[ 0.,  2.,  3.,  4.,  5.],
        [ 6.,  0.,  8.,  9., 10.],
        [11., 12.,  0., 14., 15.],
        [16., 17., 18.,  0., 20.],
        [21., 22., 23., 24.,  0.]], device='mps:0')
Elements greater than A.mean(): tensor([11., 12., 14., 15., 16., 17., 18., 20., 21., 22., 23., 24.],
       device='mps:0')


Tensor B:
 tensor([[ 95,   4,   8,  47,  35,  18,  51,  52,  86,  17],
        [ 58,  91,  23,  72,  80,  33,  53,  76,   2,   2],
        [ 99,  29,  60,  21,  53,  51, 100,   4,  97,  49],
        [ 51,  42,  24,  15,   6,  11,  55,  25,  62,  10],
  

In [92]:
# -----------------------
# SECTION 4 — Autograd Basics
# -----------------------

x = torch.tensor(3.0, requires_grad=True, device=device)
y = x**3 + 2*x
y.backward()
print("Gradient of function y is :", x.grad)

x = torch.tensor([1.0,2.0,3.0], requires_grad=True, device=device)
y = (x**2).sum()
y.backward()
print("\n\nGradient of function y is :", x.grad)

x = torch.tensor([2.0], requires_grad=True, device=device)
y = 5*(x**2) + 4*x + 1
y.backward()
print("\n\nGradient of function y is :", x.grad)

x = torch.tensor(2.0, requires_grad=True)
y = x**2
z = 3*y + 4
z.backward()
print("\n\nGradient of function z is :", x.grad)

Gradient of function y is : tensor(29., device='mps:0')


Gradient of function y is : tensor([2., 4., 6.], device='mps:0')


Gradient of function y is : tensor([24.], device='mps:0')


Gradient of function z is : tensor(12.)
