In [2]:
import torch

# Detect GPU (MPS for Apple Silicon)
device = "mps" if torch.backends.mps.is_available() else "cpu"
print("Using device:", device)


Using device: mps


🔹 Section 1 — Matrix Multiplication (torch.matmul)

In [25]:
x = torch.randn(5, device=device)
A = torch.randn(5, 5, device=device)

print(x@x)
print(A@x)
print(A@A)

print(torch.matmul(x, x))
print(torch.matmul(A, x))
print(torch.matmul(A, A))

tensor(4.2619, device='mps:0')
tensor([-0.4014, -0.0143,  1.1808,  1.4789,  1.0867], device='mps:0')
tensor([[-1.1282,  2.1120, -4.0236,  0.9736,  0.6256],
        [-0.3778,  2.2934,  1.3163, -0.4804, -1.4721],
        [-0.1757, -2.6583,  1.1988,  0.0154,  0.0072],
        [-1.2331,  0.8547, -0.5759,  0.7877, -1.4602],
        [ 0.3520, -2.5709,  1.3769, -0.7265, -0.5154]], device='mps:0')
tensor(4.2619, device='mps:0')
tensor([-0.4014, -0.0143,  1.1808,  1.4789,  1.0867], device='mps:0')
tensor([[-1.1282,  2.1120, -4.0236,  0.9736,  0.6256],
        [-0.3778,  2.2934,  1.3163, -0.4804, -1.4721],
        [-0.1757, -2.6583,  1.1988,  0.0154,  0.0072],
        [-1.2331,  0.8547, -0.5759,  0.7877, -1.4602],
        [ 0.3520, -2.5709,  1.3769, -0.7265, -0.5154]], device='mps:0')


🔹 Section 2 — Broadcasting in Matrix Multiplication

In [40]:
batch_vectors = torch.randn(10, 5, device=device)
v = torch.randn(5, device=device)


print("shape of batch_vectors:", batch_vectors.shape)
print("shape of v:", v.shape)
print("shape of batch_vectors @ v: ", torch.matmul(batch_vectors, v).shape)
print("shape of v @ batch_vectors.T: ", torch.matmul(v, batch_vectors.T).shape)

shape of batch_vectors: torch.Size([10, 5])
shape of v: torch.Size([5])
shape of batch_vectors @ v:  torch.Size([10])
shape of v @ batch_vectors.T:  torch.Size([10])


🔹 Section 3 — einsum: Explicit Control of Math

In [53]:
# Examples of einsum

a = torch.randint(1,5,(5,), device=device)
b = torch.randint(1,5,(5,), device=device)
c = torch.randint(1,5,(5,5), device=device)
d = torch.randint(1,5,(5,5), device=device)

print("A:", a)
print("B:", b)
print("C:", c)
print("D:", d)

# Dot product
print("Vector dot Product:", torch.einsum('i,i', a,b))

# Element wise product
print("Vector element wise Product:", torch.einsum('i,i->i',a,b))

# Outer product
print("Outer product:", torch.einsum('i,j->ij',a,b))

# Matrix vector multiplication

print("Matrix vector product:", torch.einsum('ij,j->i',c,b))

# Row wise dot product
print("Row wise dot product:", torch.einsum('ij,ij->i',c,d))

# Batch matrix vector multiplication
A = torch.randint(1,5,(10,5,5), device=device)
v = torch.randint(1,5,(10,5), device=device)

print("Batch matrix A:", A)
print("Batch vector v:", v)

print("Batch matrix vector product:", torch.einsum('ijk, ik->ij',A,v))

# Batch matrix matrix multiplication
B = torch.randint(1,5,(10,5,5), device=device)
print("Batch matrix B:", B)

print("Batch matrix matrix product:", torch.einsum('ijk,ikl -> ijl',A,B))

# Columns wise sum of matrix

print("Column wise sum of matrix:", torch.einsum('ij -> j',c))

# Weighted sum of features

X = torch.randint(1,5,(10,5), device=device)
w = torch.randint(1,5,(5,), device=device)
print("Feature matrix X:", X)
print("Weight vector w:", w)
print("Weighted sum of features:", torch.einsum('ij,j ->i',X,w))

# Attention score matrix

Q = torch.randint(1,5,(10,5,5), device=device)
K = torch.randint(1,5,(10,5,5), device=device)
print("Query matrix Q:", Q)
print("Key matrix K:", K)
print("Attention score matrix:", torch.einsum('ijk, ikj -> ijk',Q,K))

A: tensor([2, 4, 3, 4, 4], device='mps:0')
B: tensor([4, 2, 2, 1, 1], device='mps:0')
C: tensor([[3, 1, 2, 4, 1],
        [3, 4, 2, 3, 3],
        [4, 2, 4, 2, 2],
        [2, 3, 1, 2, 4],
        [1, 1, 3, 1, 4]], device='mps:0')
D: tensor([[2, 3, 2, 2, 3],
        [2, 4, 4, 4, 4],
        [4, 4, 2, 3, 2],
        [1, 4, 1, 2, 1],
        [1, 1, 1, 2, 4]], device='mps:0')
Vector dot Product: tensor(30, device='mps:0')
Vector element wise Product: tensor([8, 8, 6, 4, 4], device='mps:0')
Outer product: tensor([[ 8,  4,  4,  2,  2],
        [16,  8,  8,  4,  4],
        [12,  6,  6,  3,  3],
        [16,  8,  8,  4,  4],
        [16,  8,  8,  4,  4]], device='mps:0')
Matrix vector product: tensor([23, 30, 32, 22, 17], device='mps:0')
Row wise dot product: tensor([24, 54, 42, 23, 23], device='mps:0')
Batch matrix A: tensor([[[2, 4, 3, 2, 4],
         [3, 3, 3, 3, 1],
         [4, 2, 2, 1, 4],
         [2, 2, 4, 4, 4],
         [1, 1, 3, 4, 1]],

        [[2, 1, 2, 3, 1],
         [4, 1, 1

 Section 4 — Linear Algebra with torch.linalg

In [15]:
M = torch.randint(1,5,(3,3), dtype=torch.float32)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = torch.linalg.eig(M)
print("Matrix M:", M)
print("\nEigenvalues:", eigenvalues)
print("\nEigenvectors:", eigenvectors)

# SVD

U, S, Vh = torch.linalg.svd(M)
print("\nLeft singular vectors U:", U)
print("\nSingular values S:", S)
print("\nRight singular vectors Vh:", Vh)

#reconstruct M from SVD
S_matrix = torch.zeros_like(M)
S_matrix[0:S.shape[0], 0:S.shape[0]] = torch.diag(S)
M_reconstructed = U @ S_matrix @ Vh
print("\nReconstructed M from SVD:", M_reconstructed)

# Matrix Norms
frobenius_norm = torch.linalg.norm(M, ord='fro')
print("\nFrobenius norm of M:", frobenius_norm)

Matrix M: tensor([[2., 3., 3.],
        [4., 4., 3.],
        [2., 4., 2.]])

Eigenvalues: tensor([ 9.2045+0.0000j, -0.6022+0.8507j, -0.6022-0.8507j])

Eigenvectors: tensor([[-0.5039+0.0000j, -0.2036-0.5301j, -0.2036+0.5301j],
        [-0.6882+0.0000j, -0.3173+0.4021j, -0.3173-0.4021j],
        [-0.5220+0.0000j,  0.6443+0.0000j,  0.6443-0.0000j]])

Left singular vectors U: tensor([[-0.5016,  0.1036, -0.8589],
        [-0.6899, -0.6469,  0.3249],
        [-0.5220,  0.7555,  0.3959]])

Singular values S: tensor([9.2079, 1.1512, 0.9434])

Right singular vectors Vh: tensor([[-0.5220, -0.6899, -0.5016],
        [-0.7555,  0.6469, -0.1036],
        [ 0.3959,  0.3249, -0.8589]])

Reconstructed M from SVD: tensor([[2.0000, 3.0000, 3.0000],
        [4.0000, 4.0000, 3.0000],
        [2.0000, 4.0000, 2.0000]])

Frobenius norm of M: tensor(9.3274)


🔹 Section 5 — Manual Gradient Descent (Scalar Case)

In [20]:
x = torch.tensor(3.0, requires_grad=True, device=device)

for step in range(10):
    y = x**3 - 4*x
    y.backward()
    with torch.no_grad():
        x -= 0.1 * x.grad
        x.grad.zero_()
    print(f"Step {step+1}: x = {x.item()}, y = {y.item()}")

# print("Value of y:", y)
# print("Gradient dy/dx at x=3:", x.grad)

Step 1: x = 0.7000000476837158, y = 15.0
Step 2: x = 0.9530000686645508, y = -2.4570000171661377
Step 3: x = 1.0805373191833496, y = -2.946476936340332
Step 4: x = 1.1302690505981445, y = -3.060556173324585
Step 5: x = 1.1470166444778442, y = -3.0771484375
Step 6: x = 1.15232253074646, y = -3.0789973735809326
Step 7: x = 1.153968334197998, y = -3.079181671142578
Step 8: x = 1.154475450515747, y = -3.07919979095459
Step 9: x = 1.1546313762664795, y = -3.0792012214660645
Step 10: x = 1.154679298400879, y = -3.0792014598846436
